#!/bin/dash

doalsaswitch() {
if ! lspci | grep -qi audio; then
    echo No soundcard, exit
    exit
fi

while ! test -c /dev/snd/controlC0; do sleep 1;
done

if amixer get Master 2> /dev/null; then exit
elif amixer get PCM 2> /dev/null; then exit
fi

for card in 1 2 3 4 5 0; do
    if amixer -c $card get Master 2> /dev/null; then break
    elif amixer -c $card get PCM 2> /dev/null; then break
    fi
done

if [ $card != "0" ]; then
    echo write /etc/asound.conf
    echo defaults.pcm.card $card
    echo defaults.ctl.card $card
    echo defaults.pcm.card $card > /etc/asound.conf
    echo defaults.ctl.card $card >> /etc/asound.conf
fi
}

doalsaswitch > /var/log/alsaswitch.log
