#!/bin/sh

echo -e '\n'
echo "${BOLD}/$FOLDER/01-filesystem.squashfs not found!${RST}
You are maybe using an unsupported boot device (eg. RAID SCSI or SAS).
${RED}Make sure UEFI Secure Boot is disabled!${RST}
Workaround: Copy the directory /$FOLDER from your boot device to internal SATA
disk, eg. to ${BOLD}/mnt/sda1/$FOLDER${RST} or ${BOLD}C:\\$FOLDER${RST}. Then try to boot again.
Make sure that your boot parameters (cheatcodes) are correct.

${BOLD}Press ${YELLOW}space/enter ${RST}${BOLD}to unmount all devices and reboot
or ${YELLOW}any other key ${RST}${BOLD}to drop to the debug shell.${RST}"
read -s -n1 ans
if [ "$ans" = "" ]; then
    umount /mnt/* 2>/dev/null
    umount -a 2>/dev/null
    reboot -f
else
echo "${CYAN}Here is debugging shell for you, unmount all partitions
and press Ctrl+Alt+Del when you finish. Good luck!${RST}"
sh
fi
